### PR TITLE
[Fix]: validations, toasts, password visibility

### PR DESCRIPTION
**Pull request by anjali1102**

### CODE REVIEW

**Review by MaruthiPothuganti — APPROVED** [review]
Code looks good. PR can be merged

**Review by vishalg8454 — APPROVED** [review]
The features work as expected. 
Noticed this layout bug in my browser, the app takes more width than the available viewport width

image

**Comment by anjali1102** [comment]
> The features work as expected. Noticed this layout bug in my browser, the app takes more width than the available viewport width
> 
> image

@vishalg8454  buy new laptop then 😏

**Review by ashishkatiyar2404 — APPROVED** [review]
code looks good to merge.

**Pull request merged**
